### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by apenney** [sphinx-contrib/sphinxcontrib-confluencebuilder#149]
Hi,

Ran into a weirdness earlier today:

```
# Sphinx version: 1.7.7
# Python version: 2.7.15 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.10
# Last messages:
#   done
#   checking consistency...
#   done
#   preparing documents...
#   scanning for assets...
#   done
#   done
#   writing output... [ 33%] guides/aws/autoscaling_applications/index
#   writing output... [ 66%] index
#   writing output... [100%] service_guide/index
# Loaded extensions:
#   alabaster (0.7.11) from /usr/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinxcontrib.confluencebuilder (unknown version) from /usr/local/lib/python2.7/site-packages/sphinxcontrib_confluencebuilder-0.10.0.dev0-py2.7.egg/sphinxcontrib/confluencebuilder/__init__.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 325, in build
    self.builder.build_all()
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 299, in build_all
    self.build(None, summary='all source files', method='all')
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 403, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 440, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 449, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/lib/python2.7/site-packages/sphinxcontrib_confluencebuilder-0.10.0.dev0-py2.7.egg/sphinxcontrib/confluencebuilder/builder.py", line 303, in write_doc
    and node['ids'][0]
IndexError: list index out of range
```

I hacked up the code to print node['ids'] and saw:

```
['id5'] output... [100%] service_guide/index
['id6']
['id7']
['id8']
['id9']
['id10']
['id11']
['id12']
['id13']
['id14']
['id15']
['id16']
['id17']
['id18']
['id19']
['id20']
['id21']
['id22']
['id23']
['id24']
['id25']
['id26']
['id27']
['id28']
['id29']
['id30']
['id31']
['id32']
['id33']
['id34']
['id35']
['id36']
['id37']
['id38']
['id39']
['id40']
['id41']
['id42']
['id43']
['id44']
['id45']
['id46']
['id47']
['id48']
['id49']
['id50']
['id51']
['id52']
['id53']
['id54']
['id55']
['id56']
['id57']
['id58']
['id59']
['id60']
['id61']
['id62']
['id63']
['id64']
['id65']
['id66']
['id67']
['id68']
['id69']
['id70']
['id71']
['id72']
['id73']
['id74']
[]
```

I worked around this with:

```
                        if ('ids' in node
                                and len(node['ids']) > 0
                                and node['ids'][0] == title_element['refid']):
```

In builder.py and everything built, published, and looks OK.  I'm not sure what the "right" way to troubleshoot this is.  Any suggestions?! :)

**Comment by jdknight** [comment]
For sure this is an issue with this extension when parsing the document's known references. Thanks for reporting it. The logic assumes that the existence of the `ids` attribute implies that there are identifiers to work with -- and in most cases, we only deal with the first element. In most cases, there is usually one or more identifiers when the attribute exists. But, for this case, it is not (I've [seen this before](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blob/0324b8ae941e939ddfcc5335d0b591afbbd139d3/sphinxcontrib/confluencebuilder/translator.py#L797) with citation types as well).

The workaround you have provided works; however, I would suggest a tweak to the check:
```
                        if ('ids' in node and node['ids']
                                and node['ids'][0] == title_element['refid']):
```

**Comment by jdknight** [comment]
See also #154.

**Comment by jdknight** [comment]
Version 1.0 of this extension has been released which addresses the title parsing error discussed in this issue; closing.
